### ISSUE TITLE
Possible Code Cleanup

### ISSUE THREAD

**Issue by Fallenleader** [gdkchan/Ohana3DS-Rebirth#10]
http://pastebin.com/QS9uRBkh

I have provided a paste-bin of the possible issue commented out with a note, and the possible solution proposed.

Issue: at https://github.com/gdkchan/Ohana3DS-Rebirth/blob/c2371351b03dcf1d15b635b122ad27ef9e612c68/Ohana3DS%20Rebirth/FrmSettings.cs on lines 41 - 64, a function that could possibly be shrunk into a single function is split into two functions.
The reasoning behind this is not clear, and the code makes no sense. Is this required due to Visual Studio?

**Comment by gdkchan** [comment]
Because pressing the Return key (see FrmSettings_KeyDown) also performs the same action of clicking on the OK button.

**Comment by Fallenleader** [comment]
Noted. Thanks for the clarification.
