### ISSUE TITLE
Import Button doesn't work on Pokemon Overworld BCHs

### ISSUE THREAD

**Issue by igniscitrinus** [gdkchan/Ohana3DS-Rebirth#11]
Pokemon Overworld models can't be imported through the Import dialog, but they can be dragged and dropped and loaded from the Open dialog just fine.
My guess is that they're not being properly autodetected since their magic bytes are MM, as opposed to BCH.

**Comment by gdkchan** [comment]
it cant be imported because I didnt added it on the import dialog format switch case (FileIO.cs, lines 213 - 230).
