### ISSUE TITLE
Request: Sticker Star BCMDL support

### ISSUE THREAD

**Issue by mariomadproductions** [gdkchan/Ohana3DS-Rebirth#16]
PM me on GBATemp if you want examples.

**Comment by gdkchan** [comment]
I guess its ok if you upload and paste the link here on github.

**Comment by mariomadproductions** [comment]
You can decompress the files ending in z using the blz.exe from the "Nintendo DS/GBA Compressors" tool. blz.exe doesn't have support for multiple files, so to do them in batch you'll have to make a script.
https://drive.google.com/file/d/0B_yBl-184usmdkFqbTM4QzBoakE/view?usp=sharing

**Comment by mariomadproductions** [comment]
models seem to work, after decompression.
