### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Blayer98** [gdkchan/Ohana3DS-Rebirth#27]
![image](https://cloud.githubusercontent.com/assets/6663677/14403495/2bd6f022-fe50-11e5-9517-ee294008217c.png)

Not sure what's going on here...
Yes, I have disabled f.lux, which was causing an issue with texture rendering with the fragment shader.
And some models are still using the "Always use first texture" when some actually require the other option. "Use last texture when present".

**Comment by gdkchan** [comment]
Some empty material animations throws this errors. Since the list don't have any element, it will throw an exception when trying to access any element.

**Comment by Demonslayerx8** [comment]
i actually get that error when there's color animation is involved, which im pretty sure isnt figured out yet.
