### ISSUE TITLE
Inverted faces on Rhythm Thief character models

### ISSUE THREAD

**Issue by internetakias** [gdkchan/Ohana3DS-Rebirth#29]
![invertedralf](https://cloud.githubusercontent.com/assets/5077063/14508047/60726b6e-01ce-11e6-8557-66948534ff6e.PNG)

Strangely enough, exporting to obj and loading that in Metasequoia makes the model show correctly
Model: https://my.mixtape.moe/tdirbe.7z

**Comment by Demonslayerx8** [comment]
its due to the shader the game uses... this game pretty much uses the 3ds hardware to enable the shader, which Ohana doesnt do.

**Comment by internetakias** [comment]
I see. Still weird that exporting to obj magically fixes it, though

**Comment by Reisyukaku** [comment]
Yea, metaseq is weird. But that looks like inverted normals. Like the above poster said, they probably use a special shader with it like that. Maybe a toon/cell shaded one since i've seen people use that technique before.
I'll close for now since it probably is working as intended.
