### ISSUE TITLE
using Microsoft.DirectX; using Microsoft.DirectX.Direct3D; is obsolete. Causes Visual Studio to go bonkers and fails to build

### ISSUE THREAD

**Issue by Fallenleader** [gdkchan/Ohana3DS-Rebirth#32]
http://stackoverflow.com/questions/26855181/the-type-or-namespace-name-directx-does-not-exist-in-the-namespace-microsoft
As note here, managed DX is obsolete. Unfortunately, I am not fluent enough in C# or VS development to address this myself. Not sure if I am missing something needed or what, but this tool is now unbuildable for me.
This also includes other variants such as Transfigured, which yield a DX error trying to load anything 3d related (there are actual builds available for transfigured)

**Comment by Reisyukaku** [comment]
It compiles fine for me on Win7. I think you need a specific directx managed package installed. And yea, it's deprecated now, and in the past when i worked with gdkchan, we discussed this, but he mainly knew managed DX and i only knew a little OpenGL, but not enough to pull this off, so we left it for now.

**Comment by Fallenleader** [comment]
I am installing the DX SDK to see if this resolves the issue. Will report back.

**Comment by Fallenleader** [comment]
Installing the DirectX June 2010 SDK seems to resolve the issue if you recompile the program yourself.
If you run into an issue installing the SDK, there is a MSDN article on how to address this. Following that article will allow you to install it without a problem.
Officially closing this.

**Comment by hlixed** [comment]
Update from the future: I was running into crashes with an error message involving directX, and downloading the DirectX June 2010 SDK from [here](https://www.microsoft.com/en-us/download/details.aspx?id=68120) and recompiling fixed my error. Thanks, @Fallenleader!
