### ISSUE TITLE
Sun and Moon texture import error.

### ISSUE THREAD

**Issue by trainboy2019** [gdkchan/Ohana3DS-Rebirth#36]
When I try to import a texture into a sun and moon model, nothing happens. The texture doesn't change at all.

**Comment by gdkchan** [comment]
Data importing is not supported by this tool.

**Comment by trainboy2019** [comment]
I could change X and Y's textures just fine. Is it just an issue with Sun and Moon's data structure?

**Comment by CrimsonMaple** [comment]
Sun and moon is not supported at this time. Please do not assume this tool works with a game  demo released 3 days ago.

**Comment by gdkchan** [comment]
It does have a BCH texture replacer, but like the name implies it only works for BCH, and Sun/Moon uses a different format. Replacing textures on Sun/Moon format would be way easier than bch because the format is simpler and the texture have its own section, but its just not a priority atm.

**Comment by trainboy2019** [comment]
I see, thank you!
