### ISSUE TITLE
Star Rush reading texture maps issue

### ISSUE THREAD

**Issue by Kaiotiq** [gdkchan/Ohana3DS-Rebirth#38]
You need to make a patch for the Star Rush models. Most of them appear broken, because Ohana can't read the texture mapping properly.
![ohanaproblem](https://cloud.githubusercontent.com/assets/22428510/19621768/14590b0c-9891-11e6-9573-c680210573d0.png)

**Comment by gdkchan** [comment]
Are you sure those are textures? looks more like vertex colors.

**Comment by Kaiotiq** [comment]
You're clearly not understanding the problem. They LACK texture mapping, regardless of vertex colours. Here's an example.

![correctmapping](https://cloud.githubusercontent.com/assets/22428510/19627165/c5b46c14-9938-11e6-854b-198d8e8a8a36.png)

**Comment by gdkchan** [comment]
Ok I'll need the model files to analyze and fix the problem.

**Comment by Kaiotiq** [comment]
https://mega.nz/#!agkExIDT!Sj4TMbsP4C0UZBUKdD7jg2XfljvyKj2o70yN-K49U7E

**Comment by Kaiotiq** [comment]
It looks like an issue with tex coords, if I'm not mistaken.

**Comment by gdkchan** [comment]
Are you sure they are textures? Looks more like vertex colors.

**Comment by Demonslayerx8** [comment]
thats what im pretty much guessing, its either vert colors, or colored via material or shader

**Comment by Kaiotiq** [comment]
Are you blind

**Comment by Demonslayerx8** [comment]
No, but are you aware that Ohana Rebirth doesn't render models like they do on the 3ds?

Most shaders from 3ds don't render in Ohana, and they use a code in the 3ds to render properly, and thats not supported in Ohana Rebirth.

**Comment by Kaiotiq** [comment]
I think you need to learn what texture mapping is
https://en.wikipedia.org/wiki/Texture_mapping

**Comment by Demonslayerx8** [comment]
im pretty sure its a shader issue, cause its fine for me, ur GPU just doesn't support it.
![lol fail](https://cloud.githubusercontent.com/assets/17195757/19710521/f174b082-9ae3-11e6-98c6-b25dc4967b28.png)

**Comment by Kaiotiq** [comment]
> ur GPU doesn't support it

I have a GTX 780 :v

**Comment by Demonslayerx8** [comment]
but srsly.. the uv mapping is fine.. just export the model as DAE or SMD, load into a 3d software and apply the texture, u'll see that the model is fine, its just Ohana not compatible with NVidia driver or whatever.

**Comment by Kaiotiq** [comment]
How is it not compatible if I can view other models...? It seems like an odd inconsistency.

**Comment by Kaiotiq** [comment]
Plus I already tried that weeks ago. The issue here isn't on my end.

**Comment by robotortoise** [comment]
Kaiotiq, are you running f.lux? I've had problems using f.lux and Ohana at the same time.

**Comment by Kaiotiq** [comment]
No, I'm not using f.lux.

**Comment by Kaiotiq** [comment]
![issue](https://cloud.githubusercontent.com/assets/22428510/19710864/60c770ba-9b29-11e6-8231-e0d6267ab490.png)

**Comment by Kaiotiq** [comment]
![issue2](https://cloud.githubusercontent.com/assets/22428510/19710870/6835d760-9b29-11e6-84b6-98b0241a9a1d.png)

**Comment by Demonslayerx8** [comment]
So i looked more into it...

This is how it goes
UV1 - Shadering Texture
UV2 - Diffuse Texture (scale size multiplied via material)

so pretty much goes by UV layers for how the model looks. 
![uv1](https://cloud.githubusercontent.com/assets/17195757/19711013/83676fe0-9ae7-11e6-8ee7-0bbd12dd4ae3.png)
![uv2](https://cloud.githubusercontent.com/assets/17195757/19711014/8369fd64-9ae7-11e6-9745-8b61d5c89b2f.png)

**Comment by Demonslayerx8** [comment]
result of fixing the uv's
![result of uv fix](https://cloud.githubusercontent.com/assets/17195757/19711148/71015de2-9ae8-11e6-894c-b12fd23888bf.png)

**Comment by Kaiotiq** [comment]
Can you add me on Skype/Discord? So I can talk to you more about it, since I'm confused.

**Comment by Demonslayerx8** [comment]
Discord: DSX8#8339

**Comment by Demonslayerx8** [comment]
Discord: DSX8#8339
