### ISSUE TITLE
No readme!

### ISSUE THREAD

**Issue by Fallenleader** [gdkchan/Ohana3DS-Rebirth#4]
Repository should have a readme for those who havent visited the forums for instructions to build.
This can contain anything from a simple link to the forum, or even detailed instructions for build requirements.

**Comment by Fallenleader** [comment]
Solution proposed:
I can provide a readme complete with pictures on how to download and build this application. While it is simple for the tech savvy, it isn't clear to those who have no experience with Visual Studio at all.

**Comment by gdkchan** [comment]
ok, please make a PR request with the README.MD, or send it to me and Ill add it to the repo. Thanks!

**Comment by Fallenleader** [comment]
Got a means to send it? My git knowledge is extremely limited, and I have no clue how to Pull/Push.
Note: I will TRY to do so through git.

**Comment by gdkchan** [comment]
I agree that it is crappy, but since Im not going to work on this anytime soon, I decided to merge it. Thanks for the contribution.

**Comment by Fallenleader** [comment]
I apologize, I plan to make a better one in the future complete with pictures.
Things are a bit chaotic IRL and this was admittedly hastily done at the time.
