### ISSUE TITLE
 Incomplete texture

### ISSUE THREAD

**Issue by RyuSuikasou** [gdkchan/Ohana3DS-Rebirth#51]
I'm sorry I'm not good at English.
Probably,Textures "ps_Zprism_BF01" and "s20_Lift01" in "\stage\end\Prism\model\Z20_Prism_BF\normal.bch" in Super Smash Bros for 3DS are incomplete.
These have unnatural blank.

![prism](https://cloud.githubusercontent.com/assets/26084107/23400959/34f9025a-fde9-11e6-8e8b-4cc6cf213036.png)

![prism_tower_omega](https://cloud.githubusercontent.com/assets/26084107/23401187/24458086-fdea-11e6-82c1-3727e64e96a3.jpg)

**Comment by gdkchan** [comment]
[SPICA](https://github.com/gdkchan/SPICA) doesn't have this issue.

**Comment by RyuSuikasou** [comment]
I could get complete textures.
thank you very much!
