### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by melsbacksfriend** [gdkchan/Ohana3DS-Rebirth#59]
I can't seem to open anything on this but I'm not having any problems with the original Ohana 3ds.  
![ohana crash](https://user-images.githubusercontent.com/36408599/41791565-ec636fc6-760a-11e8-8c91-33d31b16b3d7.PNG)

**Comment by melsbacksfriend** [comment]
I got it working by installing DirectX.

**Comment by SuadSeen** [comment]
@melsbacksfriend I have the same problem. How can I fix it? Please tell.
