### ISSUE TITLE
Little Battlers Experience models not being parsed correctly

### ISSUE THREAD

**Issue by igniscitrinus** [gdkchan/Ohana3DS-Rebirth#6]
The vertex weights aren't being parsed correctly on .bcmdls from Little Battlers Experience.
Character models will generally have their hands and head / mouth unweighted, and LBX models are completely broken.
https://jii.moe/EyhzBunGx.7z
Here's some models and their corresponding animations to test with.

**Comment by gdkchan** [comment]
Please try commit 7b3fabc and see if it fixes the issue with "completely broken" models.

**Comment by igniscitrinus** [comment]
Confirming, robots have proper weights and animate just fine now.
Normal characters behave somewhat differently since the overweighting workaround update, but they seem to be doing better than before:
http://i.imgur.com/wMgaugY.png
When not playing any animations, they look fine, but once an animation starts playing their heads scale up.
The heads move in accordance to their weights, which is good.
