### ISSUE TITLE
Can't import models

### ISSUE THREAD

**Issue by nanogram** [gdkchan/Ohana3DS-Rebirth#62]
I know for a fact that I am using the correct model files for importing, but it throws an error.
importing textures works, but not this :/
![captdfsure](https://user-images.githubusercontent.com/14881073/45600760-92f59a80-b9c7-11e8-9cab-9e62f51c1b38.PNG)

**Comment by nanogram** [comment]
ok never mind, i figured out i needed directx in order to get it to work lol

**Comment by SuadSeen** [comment]
@nanogram I have the same problem. How can i fix it? Please tell.

**Comment by XiliSlime** [comment]
Which 3d model file format did you use to import 3d models?
