### ISSUE TITLE
UI feature requests

### ISSUE THREAD

**Issue by robotortoise** [gdkchan/Ohana3DS-Rebirth#8]
Hi, I have some UI requests.

If possible, I'd like drag and drop support for models and the import function.

I'd also like it if the default "open new file" was set to "all files" instead of only files the program recognized, as certain models, like Fire: Emblem: Awakening's models, are viewable with the program but have no extension.

The "Import" function for models and animations doesn't allow me to import files of any type, either.

These UI improvements would make the program much more usable. I tried to add them myself by copying the "drag and drop" code from Every File Explorer, but I really don't know what I'm doing.

Also, when you "open with" program on a model, and use Ohana as the program, it doesn't work correctly. I'm assuming this is related to the drag and drop issue?

Thank you!

-Robotortoise

**Comment by gdkchan** [comment]
Some of those features was implemented on commit f62bed5.

**Comment by robotortoise** [comment]
Fantastic! Thank you.

**Comment by Fallenleader** [comment]
Please mark issue as closed @robotortoise  :)
